### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by thcongp** [Adam-Kulju/Patricia#123]
Sorry but I can't know where to ask you personally. But seems like Stockfish AVX512 works better than AVX2 for me. Can you add Patricia AVX512 to the "releases" :(? I really like this engine

**Comment by Adam-Kulju** [comment]
Hi, the executables with "v4" in the name (eg patricia_4_v4.exe) are avx512 executables. I hope that helps.

**Comment by thcongp** [comment]
That's so weird, cuz sf avx512 > sf bmi2 > sf avx2 for me (my cpu is Intel Core i5 1135G7 2.40HZ). Can you make for me a bmi2 version to try :)?

**Comment by Adam-Kulju** [comment]
Are you on Windows or Linux?

**Comment by thcongp** [comment]
im currently on windows 11

**Comment by Adam-Kulju** [comment]
[patricia_4_v3.zip](https://github.com/user-attachments/files/18141934/patricia_4_v3.zip)

here you are (it's zipped to get around github not supporting raw exe uploads)
