### ISSUE TITLE
segfault on invalid input

### ISSUE THREAD

**Issue by rofl0r** [Adam-Kulju/Patricia#124]
while testing some new features of my chess gui, one of which was buggy, the following commands were sent to patricia4:

```
position fen 1Nb3k1/5ppp/2n2n2/Pp2p3/4P3/2N1bP2/1PP2rPP/1K1R1B1R w - b6 0 20 moves b8c6 c8d7 c6e5 b5b4 c3d5 f6d5 e4d5 d7a4 d5d6 a4c2 b1a2 b4b3 a2a3 c2d1 d6d7 e3c5 a3a4 f2d2 f1d3 c5e7 a5a6 d1e2 d3e2 d2b2 a6a7 b2a2 a4b5 a2a7 b5b6 a7d7 e5d7 e7a3 f3f4 g7g5 f4g5 h7h6 g5h6 b3b2 e2d3 a3b4 g2g4 b4d2 g4g5 d2c1 h1g1 b2b1q g5g6
isready
readyok
go depth 4
```

and the engine crashed. crash is reproducible with this input.

**Comment by Adam-Kulju** [comment]
What behavior would you want to see happen? I thought that the GUI is responsible for sanitizing positions and ensuring that the engines don't get fed illegal positions (Stockfish will straight up crash if you feed it invalid inputs as well).

**Comment by rofl0r** [comment]
i wasn't aware of that stockfish does that too. figured you might be interested in fixing this from a security PoV. if invalid input is detected an info line could be printed. but if you're aware of the issue and OK with it, that's fine too, so feel free to close this.

**Comment by Adam-Kulju** [comment]
This is a fun thread to read: https://github.com/official-stockfish/Stockfish/pull/4558

Ideally I would fix it eventually, but it's not very high on my list of priorities right now. Thank you for pointing it out, however!
