### ISSUE TITLE
Segmentation fault when using "go"

### ISSUE THREAD

**Issue by enfmarinho** [Adam-Kulju/Patricia#13]
<img width="1440" alt="Screenshot 2024-04-20 at 14 12 30" src="https://github.com/Adam-Kulju/Patricia/assets/120424205/360216b0-c677-4a28-a8fb-64d415393995">
Hello, i was trying to use your chess engine to have some inspiration for mine, when i have encounter that error. I am not able to run it, since it just segfaults, i don't know much, so maybe i'm just doing something dump, but for know i'm just not able to run it due to that error. For my little knowledge i think it is failing on the reset_nnue function inside the iterative_deepening. It only works when i'm in debug mode as you can see.

**Comment by Adam-Kulju** [comment]
Hi, if you want to search infinitely with Patricia, don't use "go", use "go infinite". Patricia doesn't know how to handle "go" by itself and honestly I didn't think that was valid UCI before today. Thanks for bringing it up to my attention.

**Comment by enfmarinho** [comment]
<img width="1440" alt="Screenshot 2024-04-20 at 21 03 04" src="https://github.com/Adam-Kulju/Patricia/assets/120424205/bcd19b39-872e-441e-a58a-27d711d832bc">
Sorry to bother again, seems that go infinite also don't work as expected, it just works with the command "d" witch i assume to be debug mode. If the platform matters i am running it on macos

**Comment by enfmarinho** [comment]
<img width="1440" alt="Screenshot 2024-04-20 at 21 51 15" src="https://github.com/Adam-Kulju/Patricia/assets/120424205/895ed81d-38b9-4ca0-b8cd-6d3a53dd054d">
I have added some comments to debug, and that's what i have found out.

**Comment by enfmarinho** [comment]
<img width="1440" alt="Screenshot 2024-04-20 at 21 59 23" src="https://github.com/Adam-Kulju/Patricia/assets/120424205/90aaa5d5-2528-4fc4-b22a-8a50a9a4de1d">

I have added some print statements to find out what is going on. I think its understandable what is happening from them. In the "add_to_all" function in the file "nnue.h" line 63 for some reason the for loop that is being performed go out of bounds, since the "offset" parameter is 755712 and the size of the "delta" array is 589824.

**Comment by enfmarinho** [comment]
I apologize for my dumb mistake, I forgot to use the  "position startpos" command.
