### ISSUE TITLE
Engine crashing on multiple stop commands.

### ISSUE THREAD

**Issue by R-Goc** [Adam-Kulju/Patricia#15]
Using windows v3 binary.
Steps to reproduce:
position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
go infinite
stop
stop

I don't know if sending multiple stop commands is UCI compliant. However, I saw it in the log and tested it, and the engine crashes.

**Comment by Adam-Kulju** [comment]
Thank you for reaching out. This is a bug I became aware of a couple days ago, it occurs because I force join on stop so when you send stop again it tries to join a thread that's already joined and crashes. A fix for it (along with other bugs) will be forthcoming next commit.
