### ISSUE TITLE
adding PGO

### ISSUE THREAD

**Issue by R-Goc** [Adam-Kulju/Patricia#16]
Adding PGO seems like an easy way to increase the speed of the binary, and is very easy as the makefile only targets the clang compiler. I have a naive implementation written, should I make a PR, or do you have a plan for it already?

**Comment by Adam-Kulju** [comment]
I'd appreciate if you could make the PR, so that I can then test it. I tried PGO in Willow and it lost 30 elo, so apparently it's not very easy for me!

**Comment by R-Goc** [comment]
This should probably also get closed. I don't know if you tested this as a gainer or non-reg. PGO might make more sense when the code gets bigger, but the gain will never exceed a few percent.
