### ISSUE TITLE
Question: Patricia compared Zappa Mexico II

### ISSUE THREAD

**Issue by Sing303** [Adam-Kulju/Patricia#19]
Was Patricia compared or tested in EAS tool with Zappa Mexico II engine with Dissident Aggressor settings? For me it was the most aggressive engine last time around

ZappaMexico II - Dissident Aggressor settings
UCI_ShowCurrLine=2  
Threads=auto  
Enable Null Move=2  
Enable History Pruning=2  
Enable Singular Extensions=2  
Enable Mate Extensions=2  
Enable Futility Pruning=2  
Aggressive Futility Pruning=2  
TB Min Depth=4  
Null Move R4 Min Depth=100  
Singular Margin=75  
Singular Margin PV=50  
Eval Passed Pawn Scoring=125  
Eval Pawn Scoring=135  
Eval Minor Scoring=70  
Eval Major Scoring=70  
Eval Kingsafety Scoring=500  
Internet Lag=0  
Contempt=20  
Hide Fail Highs=2  
Print PV Tips=1

**Comment by Sing303** [comment]
[Zappa Mexico 2.zip](https://github.com/user-attachments/files/15927724/Zappa.Mexico.2.zip)
Here are the engine files if you don't have one

**Comment by Sing303** [comment]
@Adam-Kulju Or maybe there are instructions on how I can check the aggressiveness of ZappaMexico myself?

**Comment by Adam-Kulju** [comment]
Sorry, I had forgotten about this issue.
A good way to check the aggressiveness of Zappa Mexico:

Get 6-7 other engines that are somewhere near the same strength as it, run a gauntlet tournament saving the PGNs somewhere (enough games for Zappa to get about 1000 wins), time control doesn't matter so 10 seconds + 0.1 seconds increment helps that process go quickly

Download Pohl's EAS tool (can be found here: https://www.sp-cc.de/eas-ratinglist.htm), copy the pgn file over too the folder that the EAS tool is in, then run the EAS tool by double clicking on it. That should give you a rating list, and you can check the EAS scores there.

(I can't test Zappa myself because the CCRL link is removed and I don't know where to find the engine anymore.)

**Comment by Adam-Kulju** [comment]
Oh wait you sent me Zappa Mexico II? Is there a Linux exe in there somewhere? If so I can test it myself

**Comment by tissatussa** [comment]
> A good way to check the aggressiveness of Zappa Mexico: Get 6-7 other engines that are somewhere near the same strength as it, run a gauntlet tournament ..

i don't get it : this will only show which engine is strongest, not its aggressiveness .. am i right ?

**Comment by Sing303** [comment]
@Adam-Kulju In the archive there is a Zappa Mexico II x64 file without ext., I think it's for linux

**Comment by Adam-Kulju** [comment]
`cutechess-cli`. The command I use is: 

```
./cutechess-cli -tournament gauntlet -rounds 750 -games 2 -engine cmd="patricia" name="Patricia 3.0" -engine cmd="viri9" name="Viri 9" -engine cmd="sp4" name="Stormphrax 4" -engine cmd="Alexandria4" name="Alex 4" -engine cmd="akimbo0.8" name="Akimbo 0.8" -engine cmd="carp3.0.1" name="Carp 3.0.1" -engine cmd="Altair6" name="Altair 6" -engine cmd="willow4.0" name="Willow 4" -repeat -recover -each tc=10+0.1 proto=uci option.Hash=32 option.Threads=1 -openings file="4moves_noob.epd" format=epd start=94 -srand 4442 -pgnout games.pgn -concurrency 28 -ratinginterval 100
```
(replace the engines with your own)

I can run the gauntlet tonight or tomorrow, no need to worry.

**Comment by Sing303** [comment]
@Adam-Kulju Are there any test results? :)

**Comment by Adam-Kulju** [comment]
I can't seem to run Zappa on my machine; the moment I start it, it prints `Couldn't allocate 67108864 bytes for hash table "Transposition Table 24" (Cannot allocate memory).` and immediately exits.

So instead, I downloaded all of Zappa's games that it's played on CCRL and ran the EAS tool on it.

```
Rank  EAS-Score  sacs   shorts  draws  moves  Engine/player 
-------------------------------------------------------------------
   1     97845  12.36%  19.51%  17.81%   62   Zappa Mexico II 64-bit  
-------------------------------------------------------------------
```

I really expected more; I understand messing with the settings could definitely make it play more aggressively, but I'm not impressed with this tbh, especially as I looked around online and found claims that it played super aggressively by default too.

**Comment by AlexBrunetti** [comment]
Hi,
I've run a [fast tournament](https://github.com/user-attachments/files/16424518/zappa_da.zip) with Zappa DA including some engines of the same level, according to [my list](http://e4e6.com):
```
  1 MinkoChess 1.3 popcnt JA        1628.0/2632
  2 Elixir 1.0                      1556.5/2632
  3 GnuCheese 1.00                  1515.5/2632
  4 Colossus 2022a                  1467.5/2618
  5 Zappa Mexico II Dissident Aggr  1442.5/2632
  6 Clovis III                      1436.5/2618
  7 Spaghet Pesto 1.0 avx2          1391.5/2618
  8 Lynx 1.5.1                      1324.0/2632
  9 Pawny 1.2 SSE4.2                1294.0/2618
 10 GreKo 2021.06                   1280.0/2632
 11 Leorik 2.3                      1279.0/2618
 12 Protej 0.6.4                    1265.0/2632
 13 K2 0.99                         1178.0/2632
 14 Odonata 0.6.2                   1010.0/2618
 15 Inanis 1.1.0 POPCNT             1010.0/2618
 16 Caissa 1.3 POPCNT-SSE4          922.0/2618
````



 If you'd like a gauntlet, let me know.

Alex

**Comment by Adam-Kulju** [comment]
Hi there Alex and thank you! I ran the EAS tool on it and got this result:

```
Rank  EAS-Score  sacs   shorts  draws  moves  Engine/player 
-------------------------------------------------------------------
   1    265286  34.15%  36.70%  09.96%   44   Protej 0.6.4  
   2    125455  19.88%  27.79%  16.54%   46   GreKo 2021.06  
   3    100313  13.46%  21.41%  16.96%   50   MinkoChess 1.3 popcnt JA  
   4     95160  14.23%  15.85%  15.42%   51   Leorik 2.3  
   5     89546  14.44%  15.54%  16.25%   53   Odonata 0.6.2  
   6     82976  05.82%  30.22%  43.33%   41   Caissa 1.3 POPCNT-SSE4  
   7     82349  11.66%  17.93%  17.31%   51   GnuCheese 1.00  
   8     80635  09.19%  20.36%  21.72%   48   Zappa Mexico II Dissident Aggressor  
   9     77307  11.73%  17.65%  18.83%   52   K2 0.99  
  10     76583  10.87%  18.45%  20.86%   51   Colossus 2022a  
  11     72619  08.80%  20.42%  26.30%   46   Inanis 1.1.0 POPCNT  
  12     63549  08.01%  17.01%  21.02%   53   Pawny 1.2 SSE4.2  
  13     62887  11.24%  22.85%  28.34%   49   Clovis III  
  14     49874  06.67%  17.88%  26.80%   51   Lynx 1.5.1  
  15     45963  07.38%  11.93%  23.68%   54   Spaghet Pesto 1.0 avx2  
  16     43929  05.39%  14.20%  25.79%   54   Elixir 1.0  
-------------------------------------------------------------------
```

I don't think Zappa Mexico II has any claim at being the most aggressive engine in the world.
