### ISSUE TITLE
Patricia 2 better

### ISSUE THREAD

**Issue by GriffinFG** [Adam-Kulju/Patricia#27]
Patricia 2 plays the opening more aggressively. Patricia 3 is more careful in the opening, and somewhere from moves 12-15 starts playing in own style. This is a little strange for the most aggressive engine. Yes, for engine versus engine games this significantly adds elo, there are no major mistakes in the opening. But for playing against a person, it is much better to implement the option for a different network. For example, the influence of NNUE 2 by default is up to turn 15. Or a separate option of 0-20 moves for a weaker but aggressive opening NNUE. And I liked Patricia 2 better for the game.

**Comment by Adam-Kulju** [comment]
Thank you for the feedback. I will implement an "aggressive openings" option that makes Patricia sacrifice from move 1 in the next release; it's definitely seeming that engine aggressiveness and human aggressiveness are two somewhat different things.

**Comment by GriffinFG** [comment]
Top chess engines are CCRL 3000-3600, 95% of players are approximately rated 800-2100.

**Comment by Adam-Kulju** [comment]
But 95% of people who are interested in chess engines (and by extension Patricia) are interested in seeing how she fares against engines, particularly strong engines.

I'll work on a "human" option that sacrifices more in the opening, it'll be out for Patricia 3.1 or 4.
