### ISSUE TITLE
UCI Specification

### ISSUE THREAD

**Issue by RandyR99** [Adam-Kulju/Patricia#28]
Thanks for sharing your engine. I notice Skill_Level and UCI_Elo are the same. Perhaps you could change Skill_Level to something similar to other engines (e.g. 1 to 20). Also, according to the [UCI specification](https://www.shredderchess.com/download/div/uci.zip), when using UCI_Elo it should always be implemented with UCI_LimitStrength. Is this something you could implement in the future?

Randy

**Comment by Adam-Kulju** [comment]
Thank you for the feedback, I will work on getting that properly implemented for Patricia 3.1. I should probably pay more attention to the UCI specs.

**Comment by GriffinFG** [comment]
Too many random moves with UCI Limit Strength option. Yes, it weakens the engine, and it is needed for weak levels. But maybe from level 1800 onwards, randomness should be reduced. It spoils the style of the engine. I played against 2000, 2200 and even at level 2400 the style of play is not natural.

**Comment by GriffinFG** [comment]
[Event "?"]
[Site "?"]
[Date "2024.08.16"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[FEN "2r3k1/1b2pp2/p2p3p/1p1Pb1p1/4P3/PPq5/3N1PPP/1B1QK2R w K - 0 26"]
[PlyCount "4"]

26. b4 {-1.52/14 4s} Qxa3 {10s} 27. O-O {-2.29/14 3s} Qxb4 {2s} *

[Event "?"]
[Site "?"]
[Date "2024.08.16"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[FEN "r1bqk2r/pp2nppp/2p1p3/b7/4P3/1QN4P/PP1B1PP1/R3K1NR w KQkq - 0 10"]
[PlyCount "37"]

10. Qc2 {-0.53/16 4s} O-O {2s} 11. Rd1 {-0.84/15 4s} Qc7 {3s} 12. Nce2 {-0.90/
15 4s} Bxd2+ {1s} 13. Qxd2 {-1.27/17 4s} Ng6 {1s} 14. Qc2 {-1.45/16 4s} e5 {1s}
15. Nc3 {-1.45/15 4s} Be6 {1s} 16. Nge2 {-1.43/15 4s} Rad8 {2s} 17. a3 {-1.45/
15 4s} Rxd1+ {2s} 18. Qxd1 {-1.89/17 4s} Rd8 {1s} 19. Qb1 {-1.91/15 4s} Bb3 {9s
} 20. a4 {-2.26/14 3s} b5 {8s} 21. axb5 {-2.11/15 4s} cxb5 {1s} 22. O-O {-2.06/
15 3s} a6 {1s} 23. Qc1 {-1.94/15 4s} Qd6 {7s} 24. Qa1 {-1.52/14 3s} Nf4 {5s}
25. Rc1 {-1.68/15 3s} Nd3 {4s} 26. Rb1 {-2.34/15 3s} Nb4 {11s} 27. Rf1 {-1.37/
15 4s} Nc2 {1s} 28. Qc1 {-1.75/14 3s} *

Here's an example. Patricia 3.1 Limit Elo 2000 specifically gives the opponent a head start. 
Well, it's not a crime, it's a question of style realism. The old Chessmaster program, TheKing engine had a similar problem with weak personalities, could give up pawns without any compensation.

In another example, the white queen and rook made many unnecessary and strange moves, as if deliberately giving up the initiative.

**Comment by Adam-Kulju** [comment]
Part of this is due Patricia playing semi-random moves in the opening, so that she'll play a bunch of different openings when you play her from startpos. I can fix this by only enabling this if it gets sent "position startpos" and not "position fen".

Do you think it would be better if Patricia played less "useless inaccuracies" and instead had a greater tendency for "human" blunders (i.e. not senselessly hanging a piece, but missing a tactic, going for a sac that turns out to be bad, etc.)?

**Comment by GriffinFG** [comment]
Each person has his own taste, also there are his own individual styles of play and favorite engines. I played a lot online against real players. And I like the realism in the game against chess engines. It's cool if I play against a chess engine and don't understand whether it's a computer or a human. If the engine gives its material without any compensation as in the given example - I don't like this.It looked like a handicap, not a sacrifice. But you need to ask others. In fact, I played little against Patricia. But I saw some moments and left a review. 
But it's a little funny. I played a small test blitz match Shredder 13 (2000 Elo) against Patricia 3.1 (2000 Elo). And Patricia without a bishop and a knight and a few pawns, it seemed to me that there simply wasn't enough material, but Patricia checkmated.
