### ISSUE TITLE
Pat 3 weaker than 3300. 

### ISSUE THREAD

**Issue by texium** [Adam-Kulju/Patricia#29]
I ran a series of matches of 2|1 CCRL blitz time control with patricia against some engines including patricia 2.
![image_2024-08-01_144155451](https://github.com/user-attachments/assets/11105135-4524-44f1-add9-dceae419f514)
 In small sample it over performed against elite leela v2 which is roughly 3450-3500. While against Elite Leela it got smoked despite it being 3350. Against patricia 2 it also did not exhibit +150-200 performance.
I'm running 180 more blitz games but it does seem weaker than expected.

**Comment by texium** [comment]
also ignore the elo it says, i just gave some elo to arena to calculate
but its prob lower

**Comment by Adam-Kulju** [comment]
Your sample size is extremely small. Patricia 3 played 30 games against Patricia 2; this is not enough to draw any meaningful conclusions from. The games against Elite Leela V2 help drive that point home; such small sample sizes are luck and nothing more.

Also, CCRL uses a different book than what you're probably using, making comparisons more difficult - the choice of book can mean the difference between a 10 elo difference and 100 elo difference (especially for really strong engines!)

On the CCRL Blitz site (https://computerchess.org.uk/ccrl/404/) Patricia 3 has already been tested and is 3298 ELO. So I guess technically she is weaker than 3300 :P

**Comment by texium** [comment]
ccrl only tests 30-40 games per engine it faces, as mentioned I left it running in a 180 game series to check further. It definitely under performs against some engines though

**Comment by texium** [comment]
despite v2 being at least 100 elo pts stronger than v1 the advantage is not seen vs patricia 3, with patricia still somehow scoring better than v1
![image_2024-08-02_021928561](https://github.com/user-attachments/assets/119f2044-3fc8-4546-8e34-ddac05c7d507)
