### ISSUE TITLE
exe not starting on Core i7-2600k, options

### ISSUE THREAD

**Issue by TapioOfTapiola** [Adam-Kulju/Patricia#34]
Hi,

first and foremost thanks for this engine, I like your direction and focus. Increasing engines from 1424154 to 1424155 elo, I don't see the need for it.

Maybe you could reverse the algorithmic ideas and create a slider 0..1, passive...aggressive :D

The executable is not running on my 2011 era computer, I think the CPU was called SandyBridge - maybe it's a CPU thing? I tested Arena and LucasChess. Starting in a cmd, it does nothing and just terminates.

Another thing, the Archimedes APK binary, there's only skill and threads option, that's all. There were so much more options before so I reckon this is a bug?

Thx

**Comment by Adam-Kulju** [comment]
Sandy Bridge CPUs don't support avx2, you need to download the v2 versions of Patricia (patricia-v2 or patricia-v2.exe).
I'm not sure what Archimedes does to create the binaries, I know that when I download Patricia and type uci it says:

```
uci
id name Patricia 3.1
id author Adam Kulju
option name Hash type spin default 32 min 1 max 131072
option name Threads type spin default 1 min 1 max 1024
option name MultiPV type spin default 1 min 1 max 255
option name UCI_LimitStrength type check default false
option name Skill_Level type spin default 20 min 1 max 20
option name UCI_Elo type spin default 3000 min 500 max 3000
uciok
```

Less options than before because the other ones were exposed for tuning and probably shouldn't be messed with by regular users.

Hope this helps!

**Comment by TapioOfTapiola** [comment]
Ah, I confused the -v2.exe with "Patricia 2" which I didn't want, thank you.

Options, it's all good, I forgot how hidden MultiPV is in the DroidFish UI.

What I still wonder is if uci_elo and skill are both being used, which one will be used...

**Comment by Adam-Kulju** [comment]
The answer is, whichever one the GUI sets last. Both of them modify the same skill level parameter internally.

**Comment by TapioOfTapiola** [comment]
Ok, ty
