### ISSUE TITLE
Other Most Aggressive Engine.

### ISSUE THREAD

**Issue by texium** [Adam-Kulju/Patricia#6]
I think from testing, though I haven't tested with yours, Little Goliath NN  3.15-3.17 is the most aggressive engine by far ( and has an aggressive boosting option that drops about 4-500 elo) but it's around 3300 and is crazy sacrificial

**Comment by Adam-Kulju** [comment]
There doesn't seem to be any Little Goliath executables for Linux that I can find, I would appreciate if you could help me find one because I would love to test it (3.15 especially is about the same strength as Patricia 2, so I could run the exact same test conditions as I did with Patricia and compare the results in a meaningful way).

**Comment by GriffinFG** [comment]
Yes, Little Goliath NN plays quite aggressively, also possible Kayra Attack 1.5, Fire 9 NN. You can also remember the old engines Ruffian and Junior. If this is a human engine, it is desirable to support "go depth" commands. It really doesn’t matter 3000 or 3200, 3400 elo. 3000 This is stronger than Nakamura and Carlsen. And if it is an aggressive engine, then it is much more difficult for a person to play. The position cannot be closed.

**Comment by Adam-Kulju** [comment]
Support for go depth and go nodes (?) is planned as of now though I'm not sure I'll remember!

**Comment by GriffinFG** [comment]
Processing over a million games CCRL TC 40/40 Engines Aggressiveness Tool. These are the results.
389001            Patricia 3.0 64-bit  CCRL TC 40/4
                                   CCRL 40/40
361488		Patricia 2.0 64-bit
360484		CDrill 1800 build 4
292585		Little Goliath Evolution 3.17 64-bit
286203		Twisted Logic 0.065e35
285467		Princhess 0.14.1 64-bit
276859		Protej 0.6.4 64-bit
259875		Detroid 0.9.0 64-bit
252799		Shield 2.0 64-bit
252005		Velvet 4.1.0 64-bit
251469		Little Goliath Evolution 3.16 64-bit
251378		Pedone 0.5 64-bit
249926		Lc0 0.19.1 w11248 64-bit
248957		Princhess 0.15.1 64-bit
248312		BACE 4.6
246084		Saturn 1.1 64-bit
245999		Shield 1.2 64-bit
240913		Princhess 0.13.0 64-bit
240696		Velvet 6.0.0 64-bit
240180		Uralochka 3.37c 64-bit
239969		Velvet 4.0.0 64-bit
238941		Houdini 6 Tactical 64-bit
236414		Seer 2.0.1 64-bit
228077		Revenge 1.0 64-bit
224212		ChessBrainVB 3.70
Princhess is also a very aggressive engine. But Princhess 0.16 64-bit is much calmer.

**Comment by Adam-Kulju** [comment]
CDrill is a funny second place - looking it up it's about 1800 strength and has only played a few hundred games. Other than that it is nice to see Patricia lapping the field.

**Comment by GriffinFG** [comment]
Yes of course the results are not very accurate, too few games. Well, the engines don't play until the checkmate. Now other results CDrill 1800 build 4 - 764 games. But the engine does play aggressively. The author Ferdinand Mosca tried to make it interesting for games against a person. His other engine Deuterium is much stronger.
***************************************************************************** 
*** Engine Aggressiveness Tool V5.61 Score points Ratinglist 
*****************************************************************************
   1    288209  48.62%  22.92%  02.59%   53   CDrill 1800 build 4
