### ISSUE TITLE
PatriciaBot @ lichess

### ISSUE THREAD

**Issue by pangamut** [Adam-Kulju/Patricia#69]
Hello, I created a Bot at Lichess that uses the Patricia engine:

https://lichess.org/@/PatriciaBot

If this is not in your interest, please let me know, I will take it down then.

It runs on a Core i7 7700 with 4 threads in a VM.

currently it accepts challenges from other Bots and humans, preferring human challengers.

best wishes,
Stephan

**Comment by Adam-Kulju** [comment]
Thank you very much, I love there being a permanent Patricia bot on lichess (I ran my own bot sometimes, but don't have a dedicated machine for it or anything like that, so I would just take it off once I was done.)

**Comment by pangamut** [comment]
Good! it runs on a Hetzner server I have anyway, so that's fine. I will leave it online for now, let's see how things go. For any proposals/remarks/wishes, please reach out to me here or on Lichess (@realPangu).
 I'll close this issue, and thanks for Patricia.

**Comment by Adam-Kulju** [comment]
Patricia 4 is now out if you wanted to update her!

**Comment by pangamut** [comment]
I actually tried, but lichess-bot has some problems with Patricia 4. It seems Patricia 4 does not respond to the configuration attempt. 
I append the output I am getting, and am looking further into it, however, I am not that familiar with lichess-bot and the python chess libraries. Will keep you updated!

Maybe you have a quick idea what might have changed in the communication behavior? 

Also, when using Patricia 4 in chessx on macOS, I get an unspecific error at the end of the game, see attached pic.

---
`[12/18/24 15:06:15] ERROR    Quitting lichess-bot due to an error:                                                                                                             lichess_bot.py:1255
                             Traceback (most recent call last):
                               File "/home/patricia2000/lichess-bot/lib/lichess_bot.py", line 1252, in start_program
                                 start_lichess_bot()
                               File "/home/patricia2000/lichess-bot/lib/lichess_bot.py", line 1189, in start_lichess_bot
                                 with engine_wrapper.create_engine(CONFIG):
                               File "/home/patricia2000/lichess-bot/lib/engine_wrapper.py", line 127, in __exit__
                                 self.quit()
                               File "/home/patricia2000/lichess-bot/lib/engine_wrapper.py", line 478, in quit
                                 self.engine.quit()
                               File "/home/patricia2000/lichess-bot/venv/lib/python3.12/site-packages/chess/engine.py", line 3016, in quit
                                 return future.result()
                                        ^^^^^^^^^^^^^^^
                               File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
                                 return self.__get_result()
                                        ^^^^^^^^^^^^^^^^^^^
                               File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
                                 raise self._exception
                             TimeoutError`

---

<img width="441" alt="Bildschirmfoto 2024-12-18 um 15 08 07" src="https://github.com/user-attachments/assets/9580f93c-33d1-4904-9df4-e34b1c83a74c" />

**Comment by pangamut** [comment]
Update: Patricia 4 works, when I do not set any options.

It seems, that Patricia 4 does not "quit", when a ici option has been set. it needs a Ctrl-C to stop it:

`patriciabot@stockfish:~$ /usr/local/bin/patricia
Patricia Chess Engine, written by Adam Kulju


uci
id name Patricia 3.1
id author Adam Kulju
option name Hash type spin default 32 min 1 max 131072
option name Threads type spin default 1 min 1 max 1024
option name MultiPV type spin default 1 min 1 max 255
option name UCI_LimitStrength type check default false
option name Skill_Level type spin default 20 min 1 max 20
option name UCI_Elo type spin default 3000 min 500 max 3000
uciok
setoption name Threads value 4
setoption name Hash value 1024
isreday
quit
patriciabot@stockfish:~$
patriciabot@stockfish:~$
patriciabot@stockfish:~$ /usr/local/bin/patricia_4_v3
Patricia Chess Engine, written by Adam Kulju


uci
id name Patricia 4.0
id author Adam Kulju
option name Hash type spin default 32 min 1 max 131072
option name Threads type spin default 1 min 1 max 1024
option name MultiPV type spin default 1 min 1 max 255
option name UCI_LimitStrength type check default false
option name Skill_Level type spin default 20 min 1 max 20
option name UCI_Elo type spin default 3000 min 500 max 3000
uciok
setoption name Threads value 4
setoption name Hash value 1024
quit

^C
patriciabot@stockfish:~$`

**Comment by pangamut** [comment]
will create a new issue :)

**Comment by hartwork** [comment]
Thanks for Patricia and the Lichess bot! My vote for a mention in the readme or for pinning the issue to make the Lichess bot easier to find. Thank you!
