### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [Adam-Kulju/Patricia#7]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by Adam-Kulju** [comment]
Patricia includes Linux executables, v3 and v2 should work on almost any computer out there. I don't have an Android machine to compile on but you should be able to easily do so from source. 

However, the fact you spammed this same issue to 75 other chess engine repositories today suggests you're acting in bad faith, so have a nice day and please consider how your best friends or parents would feel if they knew you wasted your free time like this. Thanks!
