### ISSUE TITLE
Illegal Move Returned When Patricia Mated

### ISSUE THREAD

**Issue by RandyR99** [Adam-Kulju/Patricia#78]
Hi.

I compiled version 3.1 for the Raspberry Pi for use with Picochess. When Patricia 3.1 is about to be mated it will return a best move of a1a1 which causes python-chess to crash. I only tested using UCI_Elo = 500. Using v3.0 at UCI_Elo = 1100 (which seemed to be playing much stronger than 1100 so I had to use Stockfish to get a mate) and there was no issue.

The info lines looked fine as Patricia was thinking, it's just best move was an illegal move.

Did something happen in v3.1? I hope you can help.

Randy

**Comment by Adam-Kulju** [comment]
From a quick test I can't seem to reproduce the issue. How often does she crash? Are there any positions you can load in to the GUI that make her crash immediately?

**Comment by RandyR99** [comment]
I can't be certain that Patricia is actually crashing. I received that report from the user who initially reported the problem and he stated that Patricia had crashed in 'htop' - a resource viewer for Linux. However, I just tested on an x86_64 laptop running Linux Mint with Patricia compiled as of latest commits (and running in PicoChess) and it also failed with the invalid bestmove of a1a1, but Patricia is still showing in 'htop' so I don't think it crashed itself.

Here is the game up to the point of failure (Patricia is Black):

1. e4 c5 2. Nf3 Nc6 3. Bb5 g6 4. O-O Bg7 5. c3 e5 6. d4 Nf6 7. dxe5 Nh5 8. g4 d6
9. gxh5 gxh5 10. exd6 Bf8 11. e5 Bf5 12. Kh1 Qa5 13. Bd3 Bd7 14. Bg5 Ne7 15.
Nbd2 Bc6 16. Be4 Bxe4 17. dxe7 Bc6 18. Nc4 Qb6 19. Nd6+

And the FEN:

r3kb1r/pp2Pp1p/1qbN4/2p1P1Bp/8/2P2N2/PP3P1P/R2Q1R1K b kq - 4 19

I'll next try to test outside of PicoChess.

Randy

**Comment by RandyR99** [comment]
I just tested in Arena (in Linux) and I am seeing the same issue. Here are the last 3 entries in the log (attached):

2024-09-05 11:47:28.950<--1:info multipv 1 depth 66 seldepth 24 score mate -6 nodes 44015631 nps 2626857 time 16756 pv g6h5 f1e1 f8e8 e1e5 e8e7 e5e7 h8g8 e7e8 g8h7 g2e4 h7h6 a7e3 
2024-09-05 11:47:28.950<--1:bestmove a1a1
2024-09-05 11:47:28.950*1*---------> Arena:Illegal move!: "a1a1" (Feinpruefung)
[Arena_Patricia3.1.debug.zip](https://github.com/user-attachments/files/16897888/Arena_Patricia3.1.debug.zip)

**Comment by RandyR99** [comment]
I should also mention that I compiled with g++ rather than clang++.

Randy

**Comment by Adam-Kulju** [comment]
I wasn't able to get Patricia to crash, however I did find some pretty unexpected behavior when there is a low number of legal moves (it was sometimes printing "multipv 2" when there was one legal move etc). I will make sure to iron out all errors for next release, and I hope that will solve the problem!

**Comment by RandyR99** [comment]
Ok. Thanks Adam. We will test the next version when it's released.

**Comment by gkalab** [comment]
I could reproduce this issue with a binary built for Android. With your latest commit to main (I guess in preparation for 4.0), I cannot reproduce it any more.

**Comment by RandyR99** [comment]
That's promising. Thanks, Gerhard.

**Comment by RandyR99** [comment]
Hi Adam. I just tested v4 mating Patricia using both White and Black and had no issues. I think we can call this fixed.

Randy
